/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.64
 * Generated at: 2015-10-25 01:09:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class addProduct_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Agregar Productos</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"StyleProduct.css\" media=\"screen\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"contact-form\">  \r\n");
      out.write("   <h1 align= center>Agregar producto</h1>\r\n");
      out.write("   <h2 align = center>Rellena el formulario para ingresar nuevos productos.</h2>  \r\n");
      out.write("   <p id=\"failure\">Oops... Algo anduvo mal.</p>  \r\n");
      out.write("   <p id=\"success\">Gracias, tu mensaje ha sido enviado correctamente.</p>  \r\n");
      out.write("   <form action=\"ServletRegistro\" method=\"post\">\r\n");
      out.write("      <label for=\"name\">ID: <span class=\"required\">*</span></label>  \r\n");
      out.write("      <input type=\"text\"  id= \"id\"name=\"id\" value=\"\" placeholder=\"Insertar ID\" required=\"required\" autofocus=\"autofocus\" />  \r\n");
      out.write("         \r\n");
      out.write("      <label for=\"precio\">Descripcion: <span class=\"required\">*</span></label>  \r\n");
      out.write("      <input type=\"text\" id=\"descripcion\" name=\"descripcion\" value=\"\" placeholder=\"Nombre\" required=\"required\" />  \r\n");
      out.write("         \r\n");
      out.write("      <label for=\"precio\">Precio: </label>  \r\n");
      out.write("      <input type=\"text\" id=\"precio\" name=\"precio\" value=\"\" placeholder=\"\" required=\"required\"/>  \r\n");
      out.write("      \r\n");
      out.write("      <label for=\"cantidad\">Cantidad: </label>  \r\n");
      out.write("      <input type=\"text\" id=\"cantidad\" name=\"cantidad\" value=\"\" placeholder=\"\" required=\"required\"/> \r\n");
      out.write("      \r\n");
      out.write("      <label for=\"iva\">IVA: </label>  \r\n");
      out.write("      <input type=\"text\" id=\"iva\" name=\"iva\" value=\"\" placeholder=\"Impuesto del producto\" required=\"required\"/> \r\n");
      out.write("      \r\n");
      out.write("      <label for=\"caducidad\">Fecha de Caducidad: </label>  \r\n");
      out.write("      <input type=\"text\" id=\"caducidad\" name=\"caducidad\" value=\"\" placeholder=\"Formato yyyy-mm--dd\" required=\"required\"/> \r\n");
      out.write("         \r\n");
      out.write("      <input type=\"submit\" value=\"Send away!\" id=\"submit\" />\r\n");
      out.write("   </form>  \r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
